# Generated by Django 6.0.1 on 2026-02-04 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_product_productcolor_product_productstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carName', models.CharField(max_length=50)),
                ('carPrice', models.IntegerField()),
                ('carCompany', models.CharField(max_length=50)),
                ('carModel', models.CharField(max_length=50)),
                ('carColor', models.CharField(max_length=20, null=True)),
                ('carCondition', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cars',
            },
        ),
    ]
